### PR TITLE
Switch to GitHub Actions

### PR DESCRIPTION
**Pull request by giarc3**
~~I merged in the `43-upgrade-bindgen` branch because it was needed in order to build, so this shouldn't merge until after that.~~

### CODE REVIEW

**Review by cjyar — APPROVED** [review]
Nice work!

**Comment by clintfred** [comment]
Is there value in running the Rust build separate from the yarn build since `yarn run compile` invokes `cargo`?

**Comment by giarc3** [comment]
> Is there value in running the Rust build separate from the yarn build since `yarn run compile` invokes `cargo`?

I was thinking it might be beneficial because of it running with the `beta` toolchain to try to foresee any future issues. But I could disable that job in the workflow if you think it's not needed?

**Review by clintfred — APPROVED** [review]
Talked offline. We are going to remove `cargo test` from the rust CI workflow. Then I think we're good.

**Pull request merged**
